/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package rhino.etl.hadoop.graph.thrift;

import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TEdgeOrTitanId extends org.apache.thrift.TUnion<TEdgeOrTitanId, TEdgeOrTitanId._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TEdgeOrTitanId");
  private static final org.apache.thrift.protocol.TField TITAN_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("titanId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField T_EDGE_FIELD_DESC = new org.apache.thrift.protocol.TField("tEdge", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TITAN_ID((short)1, "titanId"),
    T_EDGE((short)2, "tEdge");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TITAN_ID
          return TITAN_ID;
        case 2: // T_EDGE
          return T_EDGE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TITAN_ID, new org.apache.thrift.meta_data.FieldMetaData("titanId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.T_EDGE, new org.apache.thrift.meta_data.FieldMetaData("tEdge", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TEdge.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TEdgeOrTitanId.class, metaDataMap);
  }

  public TEdgeOrTitanId() {
    super();
  }

  public TEdgeOrTitanId(_Fields setField, Object value) {
    super(setField, value);
  }

  public TEdgeOrTitanId(TEdgeOrTitanId other) {
    super(other);
  }
  public TEdgeOrTitanId deepCopy() {
    return new TEdgeOrTitanId(this);
  }

  public static TEdgeOrTitanId titanId(long value) {
    TEdgeOrTitanId x = new TEdgeOrTitanId();
    x.setTitanId(value);
    return x;
  }

  public static TEdgeOrTitanId tEdge(TEdge value) {
    TEdgeOrTitanId x = new TEdgeOrTitanId();
    x.setTEdge(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, Object value) throws ClassCastException {
    switch (setField) {
      case TITAN_ID:
        if (value instanceof Long) {
          break;
        }
        throw new ClassCastException("Was expecting value of type Long for field 'titanId', but got " + value.getClass().getSimpleName());
      case T_EDGE:
        if (value instanceof TEdge) {
          break;
        }
        throw new ClassCastException("Was expecting value of type TEdge for field 'tEdge', but got " + value.getClass().getSimpleName());
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case TITAN_ID:
          if (field.type == TITAN_ID_FIELD_DESC.type) {
            Long titanId;
            titanId = iprot.readI64();
            return titanId;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case T_EDGE:
          if (field.type == T_EDGE_FIELD_DESC.type) {
            TEdge tEdge;
            tEdge = new TEdge();
            tEdge.read(iprot);
            return tEdge;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case TITAN_ID:
        Long titanId = (Long)value_;
        oprot.writeI64(titanId);
        return;
      case T_EDGE:
        TEdge tEdge = (TEdge)value_;
        tEdge.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case TITAN_ID:
          Long titanId;
          titanId = iprot.readI64();
          return titanId;
        case T_EDGE:
          TEdge tEdge;
          tEdge = new TEdge();
          tEdge.read(iprot);
          return tEdge;
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case TITAN_ID:
        Long titanId = (Long)value_;
        oprot.writeI64(titanId);
        return;
      case T_EDGE:
        TEdge tEdge = (TEdge)value_;
        tEdge.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case TITAN_ID:
        return TITAN_ID_FIELD_DESC;
      case T_EDGE:
        return T_EDGE_FIELD_DESC;
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public long getTitanId() {
    if (getSetField() == _Fields.TITAN_ID) {
      return (Long)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'titanId' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setTitanId(long value) {
    setField_ = _Fields.TITAN_ID;
    value_ = value;
  }

  public TEdge getTEdge() {
    if (getSetField() == _Fields.T_EDGE) {
      return (TEdge)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'tEdge' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setTEdge(TEdge value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.T_EDGE;
    value_ = value;
  }

  public boolean isSetTitanId() {
    return setField_ == _Fields.TITAN_ID;
  }


  public boolean isSetTEdge() {
    return setField_ == _Fields.T_EDGE;
  }


  public boolean equals(Object other) {
    if (other instanceof TEdgeOrTitanId) {
      return equals((TEdgeOrTitanId)other);
    } else {
      return false;
    }
  }

  public boolean equals(TEdgeOrTitanId other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(TEdgeOrTitanId other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  @Override
  public int hashCode() {
    HashCodeBuilder hcb = new HashCodeBuilder();
    hcb.append(this.getClass().getName());
    org.apache.thrift.TFieldIdEnum setField = getSetField();
    if (setField != null) {
      hcb.append(setField.getThriftFieldId());
      Object value = getFieldValue();
      if (value instanceof org.apache.thrift.TEnum) {
        hcb.append(((org.apache.thrift.TEnum)getFieldValue()).getValue());
      } else {
        hcb.append(value);
      }
    }
    return hcb.toHashCode();
  }
  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
